Display/search
Spimy/CSC1024-Assignment pull request #10
Opened 2023-11-20 06:38 UTC by LaiYW11

Added the display section. help check

2023-11-23 16:29 UTC, LaiYW11 commented on menus/display_menu.py
> +                    isbn, author, title, status = row[:4]  #to allow search function for elements ISBN, AUTHOR, TITLE ONLY
I made a mistake here. It's supposed to be isbn, author, title = row[0:3]. I will commit my final code once I fix one of the errors I am having and make a pull request.

2023-11-24 04:59 UTC, Spimy commented on menus/display_menu.py
> +                    isbn, author, title, status = row[:4]  #to allow search function for elements ISBN, AUTHOR, TITLE ONLY
The pull request is already open just make the necessary changes and I'll give it a review.

2023-11-25 14:34 UTC, Spimy requested changes

2023-11-25 14:34 UTC, Spimy commented on menus/display_menu.py
> +                    print(header_line)
Notice how the code onward is basically the same as displaying all books for tabulation? Try creating a method (function) specifically for displaying to reduce duplicated code.

2023-11-25 14:34 UTC, Spimy commented on menus/display_menu.py
> +                    self.root.display().selection()
Because you are in a while true loop, make sure you break after you display the main menu.

2023-12-03 10:28 UTC, Spimy commented
@JBBru-helloworld Can you review the code so that it can be merged to the main branch?

2023-12-03 10:29 UTC, Spimy approved these changes

2023-12-03 10:30 UTC, Spimy approved these changes

2023-12-03 14:07 UTC, Spimy approved these changes

2023-12-05 06:27 UTC, JBBru-helloworld approved these changes

2023-12-05 06:27 UTC, merged